-- INAURA 014 — Software Engineer O*NET/ESCO Grounded Requirements
-- Replaces prototype 9-skill list with traceable O*NET 15-1252 + ESCO 2512.4 mapping
-- INAURA-SE-v2-2026.01

-- Update industry_requirements for Software Engineer to use authoritative sources
-- First, remove old prototype rows for Software Engineer (they will be re-inserted with provenance)
DELETE FROM public.industry_requirements WHERE role = 'Software Engineer';

-- Insert curated O*NET/ESCO grounded requirements
INSERT INTO public.industry_requirements (role, skill, skill_category, importance, demand, interview_relevance, source, source_url, description, version, metadata) VALUES
-- CORE COMPUTER SCIENCE
('Software Engineer', 'Data Structures & Algorithms', 'CORE COMPUTER SCIENCE', 0.95, 0.90, 0.95, 'O*NET 15-1252 + ESCO 2512.4 via INAURA mapping heuristic', 'https://www.onetonline.org/link/summary/15-1252.00', 'Algorithmic complexity and systematic problem solving; O*NET Complex Problem Solving', 'INAURA-SE-v2-2026.01', '{"source_reference": "O*NET Skills: Complex Problem Solving, Critical Thinking; ESCO: analyse software specifications", "source_version": "O*NET 28.1 / ESCO v1.1.2", "source_occupation": "15-1252 Software Developers; ESCO 2512.4", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.85, "industry_confidence": 0.95, "evidence_context": "Core competency for complexity analysis and problem solving"}'::jsonb),
('Software Engineer', 'OOP', 'CORE COMPUTER SCIENCE', 0.90, 0.85, 0.80, 'ESCO 2512.4 via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Object-oriented design and patterns; ESCO use object-oriented programming', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: use object-oriented programming", "source_version": "ESCO v1.1.2", "source_occupation": "ESCO 2512.4", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.80, "industry_confidence": 0.92}'::jsonb),
('Software Engineer', 'System Design', 'ARCHITECTURE / DESIGN', 0.90, 0.85, 0.85, 'O*NET 15-1252 + ESCO via INAURA mapping heuristic', 'https://www.onetonline.org/link/summary/15-1252.00', 'Architecture and design trade-offs; O*NET Systems Analysis', 'INAURA-SE-v2-2026.01', '{"source_reference": "O*NET Skills: Systems Analysis, Systems Evaluation; ESCO: design software", "source_version": "O*NET 28.1 / ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.80, "industry_confidence": 0.92}'::jsonb),
('Software Engineer', 'Operating Systems', 'CORE COMPUTER SCIENCE', 0.75, 0.75, 0.65, 'O*NET 15-1252 via INAURA mapping heuristic', 'https://www.onetonline.org/link/summary/15-1252.00', 'OS fundamentals; O*NET Knowledge: Computers and Electronics', 'INAURA-SE-v2-2026.01', '{"source_reference": "O*NET Knowledge: Computers and Electronics", "source_version": "O*NET 28.1", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "IMPORTANT", "required_level": 0.70, "industry_confidence": 0.88}'::jsonb),
('Software Engineer', 'Computer Networks', 'CORE COMPUTER SCIENCE', 0.75, 0.75, 0.65, 'O*NET 15-1252 via INAURA mapping heuristic', 'https://www.onetonline.org/link/summary/15-1252.00', 'Network protocols and distributed communication', 'INAURA-SE-v2-2026.01', '{"source_reference": "O*NET Knowledge: Telecommunications", "source_version": "O*NET 28.1", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "IMPORTANT", "required_level": 0.70, "industry_confidence": 0.88}'::jsonb),
-- PROGRAMMING
('Software Engineer', 'Python', 'PROGRAMMING', 0.80, 0.88, 0.75, 'ESCO via INAURA mapping heuristic + Stack Overflow 2024', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'General-purpose programming (Python as INAURA heuristic exemplar)', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: computer programming, use scripting; O*NET Programming", "source_version": "ESCO v1.1.2 / O*NET 28.1", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "IMPORTANT", "required_level": 0.75, "industry_confidence": 0.90}'::jsonb),
('Software Engineer', 'Java', 'PROGRAMMING', 0.80, 0.82, 0.75, 'ESCO via INAURA mapping heuristic + Stack Overflow 2024', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Enterprise OOP programming (Java as heuristic exemplar)', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: computer programming, use OOP", "source_version": "ESCO v1.1.2 / O*NET 28.1", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "IMPORTANT", "required_level": 0.75, "industry_confidence": 0.90}'::jsonb),
-- DATA
('Software Engineer', 'SQL', 'DATA / DATABASE', 0.85, 0.88, 0.75, 'ESCO 2512.4 via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Relational querying and schema', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: manage database, query database", "source_version": "ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "IMPORTANT", "required_level": 0.80, "industry_confidence": 0.92}'::jsonb),
('Software Engineer', 'DBMS', 'DATA / DATABASE', 0.70, 0.75, 0.60, 'ESCO via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Database design and transactions', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: manage database", "source_version": "ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "RELEVANT", "required_level": 0.70, "industry_confidence": 0.88}'::jsonb),
-- SOFTWARE DEVELOPMENT
('Software Engineer', 'REST APIs', 'SOFTWARE DEVELOPMENT', 0.85, 0.88, 0.75, 'ESCO via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'HTTP APIs design and integration', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: develop software", "source_version": "ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.80, "industry_confidence": 0.90}'::jsonb),
('Software Engineer', 'Git', 'TOOLS / COLLABORATION', 0.85, 0.90, 0.60, 'ESCO + O*NET via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Version control and collaboration', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: use version control", "source_version": "ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.75, "industry_confidence": 0.92}'::jsonb),
-- QUALITY
('Software Engineer', 'Testing', 'QUALITY / TESTING', 0.80, 0.80, 0.70, 'ESCO 2512.4 via INAURA mapping heuristic', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Unit and integration testing', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO essential: test software, debug software", "source_version": "ESCO v1.1.2", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "CORE", "required_level": 0.75, "industry_confidence": 0.90}'::jsonb),
-- TOOLS
('Software Engineer', 'Docker', 'TOOLS / COLLABORATION', 0.65, 0.75, 0.55, 'ESCO optional via INAURA mapping heuristic + CNCF', 'https://esco.ec.europa.eu/en/classification/occupation?uri=http://data.europa.eu/esco/occupation/2512.4', 'Containerization (RELEVANT, heuristic)', 'INAURA-SE-v2-2026.01', '{"source_reference": "ESCO optional: use containerization; CNCF Survey", "source_version": "ESCO v1.1.2 / CNCF 2024", "mapping_version": "INAURA-SE-v2-2026.01", "retrieved_at": "2026-01-10", "role_relevance": "RELEVANT", "required_level": 0.65, "industry_confidence": 0.85}'::jsonb)
ON CONFLICT (role, skill) DO UPDATE SET
  skill_category = EXCLUDED.skill_category,
  importance = EXCLUDED.importance,
  demand = EXCLUDED.demand,
  interview_relevance = EXCLUDED.interview_relevance,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  description = EXCLUDED.description,
  version = EXCLUDED.version,
  metadata = EXCLUDED.metadata,
  updated_at = now();

comment on table public.industry_requirements is 'Industry-grounded role requirements based on O*NET/ESCO with INAURA mapping heuristics — not universally required. Software Engineer grounded in O*NET 15-1252 (28.1) and ESCO 2512.4 (v1.1.2), INAURA-SE-v2-2026.01';
